swagger: '2.0'
info:
  title: Payments MS API
  version: "0.1"
  description: Payments MS API
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    x-authentication-scheme: Bearer
    x-bearerInfoFunc: app.decode_token
paths:
  /get_all_payments:
    get:
      tags: [ Payment ]
      operationId: app.get_all_payments
      summary: Get the full payment list with details
      responses:
        200:
          description: All the payments from all users
  /make_payment/:
    post:
      tags: [ Payment ]
      operationId: app.make_payment
      summary: Create payment entity in DB
      parameters:
        - $ref: '#/parameters/payment_body'
      responses:
        200:
          description: Successfully paid
        404:
          description: Error 404, resource has not been found
parameters:
  payment_body:
    name: payment_body
    description: Make payment
    in: body
    schema:
      required:
        - shopping_cart
        - username
        - quantity
        - money
      properties:
        shopping_cart:
          type: integer
        quantity:
          type: integer
        money:
          type: number
          format: double
        username:
          type: string